version: '3.7'

services:

  fastapi:
    build: './fastapi'
    ports:
      - '8000:8000'
    depends_on:
      - rabbit
    volumes:
      - ./fastapi/:/fastapi

  rabbit:
    hostname: rabbit
    image: 'rabbitmq:3-management'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - '15672:15672'
      - '5672:5672'

  worker:
    build: './worker'
    user: nobody
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - rabbit
      - fastapi
    volumes:
      - ./worker/:/worker

  flower:
    build: './worker'
    command: celery -A tasks flower --port=5555
    ports:
      - '5555:5555'
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - fastapi
      - rabbit