version: '3.7'

services:

  fastapi:
    build: './fastapi'
    ports:
      - '8000:8000'
    depends_on:
      - rabbit
    volumes:
      - ./fastapi/:/fastapi

  rabbit:
    hostname: rabbit
    image: 'rabbitmq:3-management'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - '15672:15672'
      - '5672:5672'

  worker:
    build: './worker'
    user: nobody
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - rabbit
      - fastapi
      - db
    volumes:
      - ./worker/:/worker

  flower:
    build: './worker'
    command: celery -A tasks flower --port=5555
    ports:
      - '5555:5555'
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - fastapi
      - rabbit

  db:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'eye'


volumes:
  postgres_data: