version: '3.7'

services:

  fastapi:
    build: './fastapi'
    ports:
      - '8000:8000'
    depends_on:
      - rabbit
    volumes:
      - ./fastapi/:/fastapi

  rabbit:
    hostname: rabbit
    image: 'rabbitmq:3-management'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - '15672:15672'
      - '5672:5672'

